# Generated by Django 6.0.1 on 2026-01-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodappDB',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Food_Amount', models.FloatField()),
                ('delivery_charge', models.FloatField()),
                ('Food_name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('Mobile_no', models.IntegerField()),
            ],
        ),
    ]
